spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_paper_generation?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 1233211234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      connection-timeout: 5000
      validation-timeout: 5000
server:
  port: 80
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
