spring:
  datasource:
    url: jdbc:mysql://tx.agno.top:3306/test_paper?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: test_paper
    password: W8bmBhzJM7dhFJB3
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      connection-timeout: 5000
      validation-timeout: 5000
server:
  port: 80
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
